services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: sanghawk
      POSTGRES_PASSWORD: sanghawk
      POSTGRES_DB: pokerdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  pgdata: